server:
  port: 9999
spring:
  application:
    name: gateway-service
  cloud:
    discovery:
      enabled: true
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowed-origins:
              - "http://localhost:4200"
            allowed-methods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowed-headers:
              - "*"
            allow-credentials: true
#    gateway:
#      routes:
#        - id: r1
#          uri: http://localhost:8088
#          predicates:
#            - Path= /orders/**
#        - id: r2
#          uri: http://localhost:8087
#          predicates:
#            - Path= /products/**